Repository fossasia/open-event-wsgen, pull requests merged in 2018-03, with the labels that each got.

#1706 Changed form.js to fix issue #1702.
  form.js
  index.html
  main.css
Labels: needs-review

#1762 Track scroll fix
  src/backend/templates/tracks.hbs
Labels: needs-review

#1779 Revert "Google fonts removed"
  index.html
  src/backend/_scss/application.scss
  src/backend/_scss/fonts/_fonts.scss
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-300.eot
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-300.svg
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-300.ttf
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-300.woff
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-300.woff2
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-600.eot
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-600.svg
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-600.ttf
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-600.woff
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-600.woff2
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-regular.eot
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-regular.svg
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-regular.ttf
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-regular.woff
  src/backend/_scss/fonts/_opensans/open-sans-v15-latin-regular.woff2
  src/backend/templates/event.hbs
  src/backend/templates/rooms.hbs
  src/backend/templates/schedule.hbs
  src/backend/templates/session.hbs
  src/backend/templates/speakers.hbs
  src/backend/templates/tracks.hbs
Labels: needs-review

#1786 time error fixed
  src/backend/fold_v2.js
Labels: needs-review

#1778 Rectify Overlap in search speaker for small screen view
  src/backend/templates/speakers.hbs
Labels: invalid

#1801 room filter added
  src/backend/templates/tracks.hbs
  src/selenium/trackPage.js
Labels: ready-to-ship
